# 深度学习（Deep Learning）培训


## 根本目的：为了找出解决问题的函数。    问题-> **f**-> 解
  
### 找寻该函数的一种方法：神经网络，它是机器学习的其中一种方法 
<br/>

## 目录
### 神经网络（Neural Networks）
### ➡️卷积神经网络（Convolutional Neural Networks）⬅️
### 循环神经网络（Recurrent Neural Networks）
### 生成对抗神经网络（Generative Adversarial Networks）
<br/>

## 卷积神经网络（Convolutional Neural Networks）

### 模型评价和验证

#### 训练集和测试集
训练集：用来训练模型
测试集：用来评价模型的好坏，永远不能用测试集来训练，也要防止测试集变相泄漏到训练集中。（例如：根据测试集的好坏来调参）

In [10]:
#使用scikit-learn切分数据集
import numpy as np
from sklearn.model_selection import train_test_split

X=np.random.random((4,4))
Y=np.random.randint(2,size=(4,1))

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25)


In [11]:
X_train

array([[ 0.10575871,  0.75410023,  0.2901971 ,  0.62866254],
       [ 0.41947819,  0.37146312,  0.61168032,  0.8465467 ],
       [ 0.94173012,  0.62027886,  0.37586211,  0.04994684]])

In [12]:
X_test

array([[ 0.27371723,  0.2375995 ,  0.40185761,  0.49925464]])

In [14]:
Y_train

array([[1],
       [1],
       [0]])

In [15]:
Y_test

array([[0]])

#### 评价分类
##### 混淆矩阵（Confusion Matrix）
又称为可能性表格或是错误矩阵。可视化的看看分类效果，用来评价分类（Classification）

|     |被诊断有病      |被诊断无病     |
|---|--------------|--------------|
|有病|True Positive |False Negative|
|没病|False Positive|True Negative |

In [18]:
from sklearn.metrics import accuracy_score
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]
score=accuracy_score(y_true,y_pred) # 0和3是对的，1和2错了，所以0.5
score

0.5

#### 评价回归
##### 平均绝对误差（Mean Absolute Error）
但是有缺点就是无法微分，不能应用梯度下降的误差函数

In [23]:
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression

X=np.array([1,2,3,4]).reshape((-1,1)) # 列向量,-1表示自动推理该位置有多少个数
Y=np.array([1,2,3,4]).reshape((-1,1)) # 列向量

regression=LinearRegression()
regression.fit(X,Y)

guesses=regression.predict(X)

error=mean_absolute_error(Y,guesses)
error

0.0

##### 均方差（Mean Squared Error）
可微分，适合做可梯度下降的误差函数

In [26]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

X=np.array([1,2,3,4]).reshape((-1,1)) # 列向量,-1表示自动推理该位置有多少个数
Y=np.array([1,2,3,4]).reshape((-1,1)) # 列向量

regression=LinearRegression()
regression.fit(X,Y)

guesses=regression.predict(X)

error=mean_squared_error(Y,guesses)
error

0.0

##### $R^2$ 决定系数（$R^2$ Score）
又叫拟合优度
<img src="r2_score.jpg" width=450 height=450 />
最简模型的误差是最大的  
好的模型：越接近1，因为模型的误差相对于最简模型越小则该项越接近0

公式：  
If $\hat{y}_i$ is the predicted value of the i-th sample and y_i is the corresponding true value, then the score R² estimated over $n_{\text{samples}}$ is defined as

$R^2(y, \hat{y}) = 1 - \frac{\sum_{i=0}^{n_{\text{samples}} - 1} (y_i - \hat{y}_i)^2}{\sum_{i=0}^{n_\text{samples} - 1} (y_i - \bar{y})^2}$

where $\bar{y} =  \frac{1}{n_{\text{samples}}} \sum_{i=0}^{n_{\text{samples}} - 1} y_i$.

In [27]:
from sklearn.metrics import r2_score
y_true=np.array([1,2,4])
y_pred=np.array([1.3,2.5,3.7])
score=r2_score(y_true,y_pred)
score

0.90785714285714292

##### 模型复杂度图（Model Complexity Graph）
欠拟合（underfitting）：训练集上表现的不好。 Error due to bias  
过拟合（overfitting）：训练集上变现的太好，以至于试图记住训练集。 Error due to variance

<img src="error_from_where.jpg" width=450 height=450 />
<img src="error_from_which.jpg" width=450 height=450 />

知道了欠拟合和过拟合的情况，就能运用验证集来挑选模型的拟合程度
<img src="cross_validation.jpg" width=450 height=450 />
<img src="model_complexity_graph.jpg" width=550 height=550 />

##### K-Fold Cross Validation
<img src="k_fold_cross_validation.jpg" width=450 height=450 />

In [36]:
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])

kf = KFold(n_splits=2,shuffle=False)  #做两次K-Fold
for train_index, test_index in kf.split(X):  #每次取出对应的索引
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("TRAIN:", train_index, "TEST:", test_index)
    print("TRAIN DATA:", X_train.tolist(), "TRAIN LABEL:",y_train.tolist(), "TEST:", X_test.tolist(),"TEST LABEL:",y_test.tolist())

TRAIN: [2 3] TEST: [0 1]
TRAIN DATA: [[1, 2], [3, 4]] TRAIN LABEL: [3, 4] TEST: [[1, 2], [3, 4]] TEST LABEL: [1, 2]
TRAIN: [0 1] TEST: [2 3]
TRAIN DATA: [[1, 2], [3, 4]] TRAIN LABEL: [1, 2] TEST: [[1, 2], [3, 4]] TEST LABEL: [3, 4]
